<?php

namespace App\Providers;


use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\View;
use Illuminate\Support\ServiceProvider;



class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {




        View::composer('*',function (){
            //all
            $provinces=[
                array(
                  'code'=>1,
                   'nepali_name'=>'प्रदेश १',
                    'english_name'=>'State 1'
                ),
                array(
                    'code'=>2,
                    'nepali_name'=>'प्रदेश २',
                    'english_name'=>'State 2'
                ),
                array(
                    'code'=>3,
                    'nepali_name'=>'प्रदेश ३',
                    'english_name'=>'State 3'
                ),
                array(
                    'code'=>4,
                    'nepali_name'=>'प्रदेश ४',
                    'english_name'=>'State 4'
                ),
                array(
                    'code'=>5,
                    'nepali_name'=>'प्रदेश ५',
                    'english_name'=>'State 5'
                ),
                array(
                    'code'=>6,
                    'nepali_name'=>'प्रदेश ६',
                    'english_name'=>'State 6'
                ),
                array(
                    'code'=>7,
                    'nepali_name'=>'प्रदेश ७',
                    'english_name'=>'State 7'
                ),
            ];
            $districts=array(
                [1,1,"TAPLEJUNG","ताप्लेजुङ",101],
                [2,2,"SANKHUWASABHA","संखुवासभा",102],
                [3,3,"SOLUKHUMBU","सोलुखुम्बु",103],
                [4,4,"OKHALDHUNGA","ओखलढुङ्गा",104],
                [5,5,"KHOTANG","खोटाङ",105],
                [6,6,"BHOJPUR","भोजपुर",106],
                [7,7,"DHANKUTA","धनकुटा",107],
                [8,8,"TERHATHUM","तेह्रथुम",108],
                [9,9,"PANCHTHAR","पाँचथर",109],
                [10,10,"ILAM","इलाम",110],
                [11,11,"JHAPA","झापा",111],
                [12,12,"MORANG","मोरङ",112],
                [13,13,"SUNSARI","सुनसरी",113],
                [14,14,"UDAYAPUR","उदयपुर",114],
                [15,15,"SAPTARI","सप्तरी",201],
                [16,16,"SIRAHA","सिरहा",202],
                [17,17,"DHANUSA","धनुषा",203],
                [18,18,"MAHOTTARI","महोत्तरी",204],
                [19,19,"SARLAHI","सर्लाही",205],
                [20,20,"RAUTAHAT ","रौतहट",206],
                [21,21,"BARA","बारा",207],
                [22,22,"PARSA","पर्सा",208],
                [23,23,"DOLAKHA","दोलखा",301],
                [24,24,"SINDHUPALCHOK","सिन्धुपाल्चोक",302],
                [25,25,"RASUWA","रसुवा",303],
                [26,26,"DHADING","धादिङ",304],
                [27,27,"NUWAKOT","नुवाकोट",305],
                [28,28,"KATHMANDU","काठमाडौँ",306],
                [29,29,"BHAKTAPUR","भक्तपुर",307],
                [30,30,"LALITPUR","ललितपुर",308],
                [31,31,"KAVREPALANCHOK","काभ्रेपलाञ्चोक",309],
                [32,32,"RAMECHHAP","रामेछाप",310],
                [33,33,"SINDHULI","सिन्धुली",311],
                [34,34,"MAKWANPUR","मकवानपुर",312],
                [35,35,"CHITAWAN","चितवन",313],
                [36,36,"GORKHA","गोरखा",401],
                [37,37,"MANANG","मनाङ",402],
                [38,38,"MUSTANG","मुस्ताङ",403],
                [39,39,"MYAGDI","म्याग्दी",404],
                [40,40,"KASKI","कास्की",405],
                [41,41,"LAMJUNG","लमजुङ",406],
                [42,42,"TANAHU","तनहुँ",407],
                [43,43,"NAWALPARASI EAST","नवलपरासी (पूर्व)",408],
                [44,44,"SYANGJA","स्याङजा",409],
                [45,45,"PARBAT","पर्वत",410],
                [46,46,"BAGLUNG","बागलुङ",411],
                [47,47,"RUKUM EAST","रुकुम (पूर्वी भाग)",501],
                [48,48,"ROLPA","रोल्पा",502],
                [49,49,"PYUTHAN","प्यूठान",503],
                [50,50,"GULMI","गुल्मी",504],
                [51,51,"ARGHAKHANCHI","अर्घाखाँची",505],
                [52,52,"PALPA","पाल्पा",506],
                [53,53,"NAWALPARASI WEST","नवलपरासी(पश्चिम)",507],
                [54,54,"RUPANDEHI","रुपन्देही",508],
                [55,55,"KAPILBASTU","कपिलवस्तु",509],
                [56,56,"DANG","दाङ",510],
                [57,57,"BANKE","बाँके",511],
                [58,58,"BARDIYA","बर्दिया",512],
                [59,59,"DOLPA","डोल्पा",601],
                [60,60,"MUGU","मुगु",602],
                [61,61,"HUMLA","हुम्ला",603],
                [62,62,"JUMLA","जुम्ला",604],
                [63,63,"KALIKOT","कालिकोट",605],
                [64,64,"DAILEKH","दैलेख",606],
                [65,65,"JAJARKOT","जाजरकोट",607],
                [66,66,"RUKUM WEST","रुकुम (पश्चिम भाग)",608],
                [67,67,"SALYAN","सल्यान",609],
                [68,68,"SURKHET","सुर्खेत",610],
                [69,69,"BAJURA","बाजुरा",701],
                [70,70,"BAJHANG","बझाङ",702],
                [71,71,"DARCHULA","दार्चुला",703],
                [72,72,"BAITADI","बैतडी",704],
                [73,73,"DADELDHURA","डँडेलधुरा",705],
                [74,74,"DOTI","डोटी",706],
                [75,75,"ACHHAM","अछाम",707],
                [76,76,"KAILALI","कैलाली",708],
                [77,77,"KANCHANPUR","कञ्चनपुर",709]
            );
            $local_bodies=array(

                    [1,1,"Taplejung","Phaktanlung Rural Municipality","फक्ताङ्लुङ्ग गाउँपालिका",10101],
                    [2,2,"Taplejung","Mikwakhola Rural Municipality","मिक्वाखोला गाउँपालिका",10102],
                    [3,3,"Taplejung","Meringden Rural Municipality","मेरिङ्गदेन गाउँपालिका",10103],
                    [4,4,"Taplejung","Maiwakhola Rural Municipality","मैवाखोला गाउँपालिका",10104],
                    [5,5,"Taplejung","Aatharai Tribeni Rural Municipality","आठराई त्रिवेणी गाउँपालिका",10105],
                    [6,6,"Taplejung","Phungling Municipality","फुङलिङ्ग नगरपालिका",10106],
                    [7,7,"Taplejung","Yangwarak Rural Municipality","याङ्वरक गाउँपालिका",10107],
                    [8,8,"Taplejung","Sirijanga Rural Municipality","सिरीजङ्गा गाउंपालिका",10108],
                    [9,9,"Taplejung","Sidingba Rural Municipality","सिदिङ्गवा गाउँपालिका",10109],
                    [10,10,"Sankhuwasabha","Bhotkhola Rural Municipality","भोटखोला गाउँपालिका",10201],
                    [11,11,"Sankhuwasabha","Makalu Rural Municipality","मकालु गाउँपालिका",10202],
                    [12,12,"Sankhuwasabha","Silichong Rural Municipality","सिलीचोङ गाउँपालिका",10203],
                    [13,13,"Sankhuwasabha","Chichila Rural Municipality","चिचिला गाउँपालिका",10204],
                    [14,14,"Sankhuwasabha","Sabhapokhari Rural Municipality","सभापोखरी गाउँपालिका",10205],
                    [15,15,"Sankhuwasabha","Khandabari Municipality","खाँदबारी नगरपालिका",10206],
                    [16,16,"Sankhuwasabha","Panchakhapan Municipality","पाँचखपन नगरपालिका",10207],
                    [17,17,"Sankhuwasabha","Chainapur Municipality","चैनपुर नगरपालिका",10208],
                    [18,18,"Sankhuwasabha","Madi Municipality","मादी नगरपालिका",10209],
                    [19,19,"Sankhuwasabha","Dharmadevi Municipality","धर्मदेवी नगरपालिका",10210],
                    [20,20,"Solukhumbu","Khumbu Pasanglhamu Rural Municipality","खुम्बु पासाङल्हामु गाउँपालिका",10301],
                    [21,21,"Solukhumbu","Mahakulung Rural Municipality","माहाकुलुङ गाउँपालिका",10302],
                    [22,22,"Solukhumbu","Sotang Rural Municipality","सोताङ गाउँपालिका",10303],
                    [23,23,"Solukhumbu","Dhudhakoshi Rural Municipality","दुधकोशी गाउँपालिका",10304],
                    [24,24,"Solukhumbu","Dhudha Koushika Rural Municipality","दुधकौशिका गाउँपालिका",10305],
                    [25,25,"Solukhumbu","Necha Salyan Rural Municipality","नेचासल्यान गाउँपालिका",10306],
                    [26,26,"Solukhumbu","Solu Dhudhakunda Municipality","सोलुदुधकुण्ड नगरपालिका",10307],
                    [27,27,"Solukhumbu","Likhu Pike Rural Municipality","लिखु पिके गाउँपालिका",10308],
                    [28,28,"Okhaldhunga","Chishankhu Gadhi Rural Municipality","चिशंखुगढी गाउँपालिका",10401],
                    [29,29,"Okhaldhunga","Siddhicharan Municipality","सिद्धिचरण नगरपालिका",10402],
                    [30,30,"Okhaldhunga","Molung Rural Municipality","मोलुङ्ग गाउँपालिका",10403],
                    [31,31,"Okhaldhunga","Khiji Demba Rural Municipality","खिजीदेम्बा गाउँपालिका",10404],
                    [32,32,"Okhaldhunga","Likhu Rural Municipality","लिखु गाउँपालिका",10405],
                    [33,33,"Okhaldhunga","Champadevi Rural Municipality","चम्पादेवी गाउँपालिका",10406],
                    [34,34,"Okhaldhunga","Sunkoshi Rural Municipality","सुनकोशी गाउँपालिका",10407],
                    [35,35,"Okhaldhunga","Manebhanjyang Rural Municipality","मानेभन्ज्याङ्ग गाउँपालिका",10408],
                    [36,36,"Khotang","Kepilasgadhi Rural Municipality","केपिलासगढी गाउँपालिका",10501],
                    [37,37,"Khotang","Aiselukharka Rural Municipality","ऐसेलुखर्क गाउँपालिका",10502],
                    [38,38,"Khotang","Lamidanda Rural Municipality","लामिडाँडा गाउँपालिका",10503],
                    [39,39,"Khotang","Halesi Tuwachung Municipality","हलेसी तुवाचुङ नगरपालिका",10504],
                    [40,40,"Khotang","Rupakot Majhuwagadhi Municipality","रुपाकोट मझुवागढी नगरपालिका",10505],
                    [41,41,"Khotang","Sakela Rural Municipality","साकेला गाउँपालिका",10506],
                    [42,42,"Khotang","Diprung Rural Municipality","दिप्रुङ्ग गाउँपालिका",10507],
                    [43,43,"Khotang","Khotehang Rural Municipality","खोटेहाङ गाउँपालिका",10508],
                    [44,44,"Khotang","Jante Dhunga Rural Municipality","जन्तेढुङ्गा गाउँपालिका",10509],
                    [45,45,"Khotang","Baraha Pokhari Rural Municipality","बराहपोखरी गाउँपालिका",10510],
                    [46,46,"Bhojpur","Shadananda Municipality","षडानन्द नगरपालिका",10601],
                    [47,47,"Bhojpur","Salpa Silichho Rural Municipality","साल्पासिलिछो गाउँपालिका",10602],
                    [48,48,"Bhojpur","Tyamke Maiyum Rural Municipality","ट्याम्के मैयुम गाउँपालिका",10603],
                    [49,49,"Bhojpur","Bhojpur Municipality","भोजपुर नगरपालिका",10604],
                    [50,50,"Bhojpur","Arun Rural Municipality","अरुण गाउँपालिका",10605],
                    [51,51,"Bhojpur","Pauwa Dunma Rural Municipality","पौवा दुङ्मा गाउँपालिका",10606],
                    [52,52,"Bhojpur","Ramprasad Rai Rural Municipality","रामप्रसाद राई गाउँपालिका",10607],
                    [53,53,"Bhojpur","Hatuwagadhi Rural Municipality","हतुवागढी गाउँपालिका",10608],
                    [54,54,"Bhojpur","Aamchowk Rural Municipality","आमचोक गाउँपालिका",10609],
                    [55,55,"Dhankuta","Mahalaxmi Municipality","महालक्ष्मी नगरपालिका",10701],
                    [56,56,"Dhankuta","Pakhribas Municipality","पाख्रिबास नगरपालिका",10702],
                    [57,57,"Dhankuta","Chhathar Jorpati Rural Municipality","छथर जोरपाटी गाउँपालिका",10703],
                    [58,58,"Dhankuta","Dhankuta Municipality","धनकुटा नगरपालिका",10704],
                    [59,59,"Dhankuta","Khalsa Chhintang Sahidbhumi Rural Municipality","खाल्सा छिन्ताङ्ग सहीदभूमि गाउँपालिका",10705],
                    [60,60,"Dhankuta","Sangurigadhi Rural Municipality","साँगुरीगढी गाउँपालिका",10706],
                    [61,61,"Dhankuta","Chaubise Rural Municipality","चौविसे गाउँपालिका",10707],
                    [62,62,"Terhathum","Aatharai Rural Municipality","आठराई गाउँपालिका",10801],
                    [63,63,"Terhathum","Phedap Rural Municipality","फेदाप गाउँपालिका",10802],
                    [64,64,"Terhathum","Menchhayayem Rural Municipality","मेन्छयायेम गाउँपालिका",10803],
                    [65,65,"Terhathum","Myanglung Municipality","म्याङ्गलुङ्ग नगरपालिका",10804],
                    [66,66,"Terhathum","Laligurans Municipality","लालीगुराँस नगरपालिका",10805],
                    [67,67,"Terhathum","Chhathar Rural Municipality","छथर गाउँपालिका",10806],
                    [68,68,"Panchthar","Yangbarak Rural Municipality","याङवरक गाउँपालिका",10901],
                    [69,69,"Panchthar","Hilihan Rural Municipality","हिलिहाङ्ग गाउँपालिका",10902],
                    [70,70,"Panchthar","Falelung Rural Municipality","फालेलुङ्ग गाउँपालिका",10903],
                    [71,71,"Panchthar","Phidim Municipality","फिदिम नगरपालिका",10904],
                    [72,72,"Panchthar","Falgunanda Rural Municipality","फाल्गुनन्द गाउँपालिका",10905],
                    [73,73,"Panchthar","Kummayak Rural Municipality","कुम्मायक गाउँपालिका",10906],
                    [74,74,"Panchthar","Tumbewa Rural Municipality","तुम्बेवा गाउँपालिका",10907],
                    [75,75,"Panchthar","Miklajung Rural Municipality","मिक्लाजुङ गाउँपालिका",10908],
                    [76,76,"Ilam","Mai Jogmai Rural Municipality","माई जोगमाई गाउँपालिका",11001],
                    [77,77,"Ilam","Sandakpur Rural Municipality","सन्दकपुर गाउँपालिका",11002],
                    [78,78,"Ilam","Ilam Municipality","ईलाम नगरपालिका",11003],
                    [79,79,"Ilam","Deumai Municipality","देउमाई नगरपालिका",11004],
                    [80,80,"Ilam","Fakfokathum Rural Municipality","फाकफोकथुम गाउँपालिका",11005],
                    [81,81,"Ilam","Mangsebung Rural Municipality","माङसेबुङ गाउँपालिका",11006],
                    [82,82,"Ilam","Chulachuli Rural Municipality","चुलाचुली गाउँपालिका",11007],
                    [83,83,"Ilam","Mai Municipality","माई नगरपालिका",11008],
                    [84,84,"Ilam","Suryodaya Municipality","सूर्योदय नगरपालिका",11009],
                    [85,85,"Ilam","Rong Rural Municipality","रोङ गाउँपालिका",11010],
                    [86,86,"Jhapa","Mechinagar Municipality","मेचीनगर नगरपालिका",11101],
                    [87,87,"Jhapa","Buddhashanti Rural Municipality","बुद्धशान्ति गाउँपालिका",11102],
                    [88,88,"Jhapa","Arjundhara Municipality","अर्जुनधारा नगरपालिका",11103],
                    [89,89,"Jhapa","Kankai Municipality","कन्काई नगरपालिका",11104],
                    [90,90,"Jhapa","Shivasatakshi Municipality","शिवसताक्षी नगरपालिका",11105],
                    [91,91,"Jhapa","Kamal Rural Municipality","कमल गाउँपालिका",11106],
                    [92,92,"Jhapa","Damak Municipality","दमक नगरपालिका",11107],
                    [93,93,"Jhapa","Gauradaha Municipality","गौरादह नगरपालिका",11108],
                    [94,94,"Jhapa","Gauriganj Rural Municipality","गौरिगञ्ज गाउँपालिका",11109],
                    [95,95,"Jhapa","Jhapa Rural Municipality","झापा गाउँपालिका",11110],
                    [96,96,"Jhapa","Barhadashi Rural Municipality","बाह्रदशी गाउँपालिका",11111],
                    [97,97,"Jhapa","Birtamod Municipality","बिर्तामोड नगरपालिका",11112],
                    [98,98,"Jhapa","Haldibari Rural Municipality","हल्दीबारी गाउँपालिका",11113],
                    [99,99,"Jhapa","Bhadrapur Municipality","भद्रपुर नगरपालिका",11114],
                    [100,100,"Jhapa","Kachanakawal Rural Municipality","कचनकवल गाउँपालिका",11115],
                    [101,101,"Morang","Miklajung Rural Municipality","मिक्लाजुङ्ग गाउँपालिका",11201],
                    [102,102,"Morang","Letang Municipality","लेटाङ नगरपालिका",11202],
                    [103,103,"Morang","Kerabari Rural Municipality","केराबारी गाउँपालिका",11203],
                    [104,104,"Morang","Sundarharaicha Municipality","सुन्दरहरैंचा नगरपालिका",11204],
                    [105,105,"Morang","Belbari Municipality","बेलबारी नगरपालिका",11205],
                    [106,106,"Morang","Kanepokhari Rural Municipality","कानेपोखरी गाउँपालिका",11206],
                    [107,107,"Morang","Pathari Shanishchare Municipality","पथरी शनिश्चरे नगरपालिका",11207],
                    [108,108,"Morang","Urlabari Municipality","उर्लाबारी नगरपालिका",11208],
                    [109,109,"Morang","Ratuwamai Municipality","रतुवामाई नगरपालिका",11209],
                    [110,110,"Morang","Sunwarshi Municipality","सुनवर्षी नगरपालिका",11210],
                    [111,111,"Morang","Rangeli Municipality","रंगेली नगरपालिका",11211],
                    [112,112,"Morang","Gramthan Rural Municipality","ग्रामथान गाउँपालिका",11212],
                    [113,113,"Morang","Budhiganga Rural Municipality","बुढीगंगा गाउँपालिका",11213],
                    [114,114,"Morang","Biratnagar Metropolitian City","बिराटनगर महानगरपालिका",11214],
                    [115,115,"Morang","Katahari Rural Municipality","कटहरी गाउँपालिका",11215],
                    [116,116,"Morang","Dhanapalthan Rural Municipality","धनपालथान गाउँपालिका",11216],
                    [117,117,"Morang","Jahada Rural Municipality","जहदा गाउँपालिका",11217],
                    [118,118,"Sunsari","Dharan Sub-Metropolitian City","धरान उपमहानगरपालिका",11301],
                    [119,119,"Sunsari","Baraha Municipality","बराह नगरपालिका",11302],
                    [120,120,"Sunsari","Koshi Rural Municipality","कोशी गाउँपालिका",11303],
                    [121,121,"Sunsari","Bhokraha Rural Municipality","भोक्राहा गाउँपालिका",11304],
                    [122,122,"Sunsari","Ramdhuni Municipality","रामधुनी नगरपालिका",11305],
                    [123,123,"Sunsari","Itahari Sub-Metropolitian City","ईटहरी उपमहानगरपालिका",11306],
                    [124,124,"Sunsari","Duhabi Municipality","दुहबी नगरपालिका",11307],
                    [125,125,"Sunsari","Gadhi Rural Municipality","गढी गाउँपालिका",11308],
                    [126,126,"Sunsari","Inaruwa Municipality","इनरुवा नगरपालिका",11309],
                    [127,127,"Sunsari","Harinagara Rural Municipality","हरिनगरा गाउँपालिका",11310],
                    [128,128,"Sunsari","Dewangunj Rural Municipality","देवानगन्ज गाउँपालिका",11311],
                    [129,129,"Sunsari","Barju Rural Municipality","बर्जु गाउँपालिका",11312],
                    [130,130,"Udayapur","Belaka Municipality","बेलका नगरपालिका",11401],
                    [131,131,"Udayapur","Chaudandigadhi Municipality","चौदण्डीगढी नगरपालिका",11402],
                    [132,132,"Udayapur","Triyuga Municipality","त्रियुगा नगरपालिका",11403],
                    [133,133,"Udayapur","Rautamai Rural Municipality","रौतामाई गाउँपालिका",11404],
                    [134,134,"Udayapur","Sunkoshi Rural Municipality","सुनकोशी गाउँपालिका",11405],
                    [135,135,"Udayapur","Tapli Rural Municipality","ताप्ली गाउँपालिका",11406],
                    [136,136,"Udayapur","Katari Municipality","कटारी नगरपालिका",11407],
                    [137,137,"Udayapur","Udayapurgadhi Rural Municipality","उदयपुरगढी गाउँपालिका",11408],
                    [138,138,"Saptari","Saptakoshi Municipality","सप्तकोशी नगरपालिका",20101],
                    [139,139,"Saptari","Kanchanrup Municipality","कन्चनरुप नगरपालिका",20102],
                    [140,140,"Saptari","Agnisair Krishna Sabaran Rural Municipality","अग्निसाइर कृष्ण सवरन गाउँपालिका",20103],
                    [141,141,"Saptari","Rupani Rural Municipality","रुपनी गाउँपालिका",20104],
                    [142,142,"Saptari","Shambhunath Municipality","शम्भुनाथ नगरपालिका",20105],
                    [143,143,"Saptari","Khadak Municipality","खडक नगरपालिका",20106],
                    [144,144,"Saptari","Surunga Municipality","सुरुङ्गा नगरपालिका",20107],
                    [145,145,"Saptari","Balan-Bihul Rural Municipality","बलान बिहुल गाउँपालिका",20108],
                    [146,146,"Saptari","BodeBarsain Municipality","बोदेबरसाईन नगरपालिका",20109],
                    [147,147,"Saptari","Dakneshwori Municipality","डाक्नेश्वरी नगरपालिका",20110],
                    [148,148,"Saptari","Belhi Chapena Rural Municipality","बेल्ही चपेना गाउँपालिका",20111],
                    [149,149,"Saptari","Bishnupur Rural Municipality","बिष्णुपुर गाउँपालिका",20112],
                    [150,150,"Saptari","Rajbiraj Municipality","राजविराज नगरपालिका",20113],
                    [151,151,"Saptari","Mahadewa Rural Municipality","महादेवा गाउँपालिका",20114],
                    [152,152,"Saptari","Tirahut Rural Municipality","तिरहुत गाउँपालिका",20115],
                    [153,153,"Saptari","Hanumannagar Kankalini Municipality","हनुमाननगर कङ्कालिनी नगरपालिका",20116],
                    [154,154,"Saptari","Tilathi Koiladi Rural Municipality","तिलाठी कोईलाडी गाउँपालिका",20117],
                    [155,155,"Saptari","Chhinnamasta Rural Municipality","छिन्नमस्ता गाउँपालिका",20118],
                    [156,156,"Siraha","Lahan Municipality","लहान नगरपालिका",20201],
                    [157,157,"Siraha","Dhangadhimai Municipality","धनगढीमाई नगरपालिका",20202],
                    [158,158,"Siraha","Golbazar Municipality","गोलबजार नगरपालिका",20203],
                    [159,159,"Siraha","Mirchaiya Municipality","मिर्चेया नगरपालिका",20204],
                    [160,160,"Siraha","Karjanha Municipality","कर्जन्हा नगरपालिका",20205],
                    [161,161,"Siraha","Kalyanpur Municipality","कल्याणपुर नगरपालिका",20206],
                    [162,162,"Siraha","Naraha Rural Municipality","नरहा गाउँपालिका",20207],
                    [163,163,"Siraha","Bishnupur Rural Municipality","विष्णुपुर गाउँपालिका",20208],
                    [164,164,"Siraha","Arnama Rural Municipality","अर्नमा गाउँपालिका",20209],
                    [165,165,"Siraha","Sukhipur Municipality","सुखीपुर नगरपालिका",20210],
                    [166,166,"Siraha","Laxmipur Patari Rural Municipality","लक्ष्मीपुर पतारी गाउँपालिका",20211],
                    [167,167,"Siraha","Sakhuwa Nankarkatti Rural Municipality","सखुवानान्कारकट्टी गाउँपालिका",20212],
                    [168,168,"Siraha","Bhagawanpur Rural Municipality","भगवानपुर गाउँपालिका",20213],
                    [169,169,"Siraha","Nawarajpur Rural Municipality","नवराजपुर गाउँपालिका",20214],
                    [170,170,"Siraha","Bariyarpatti Rural Municipality","बरियारपट्टी गाउँपालिका",20215],
                    [171,171,"Siraha","Aurahi Rural Municipality","औरही गाउँपालिका",20216],
                    [172,172,"Siraha","Siraha Municipality","सिराहा नगरपालिका",20217],
                    [173,173,"Dhanusa","Ganeshman Charnath Municipality","गणेशमान चारनाथ नगरपालिका",20301],
                    [174,174,"Dhanusa","Dhanushadham Municipality","धनुषाधाम नगरपालिका",20302],
                    [175,175,"Dhanusa","Mithila Municipality","मिथिला नगरपालिका",20303],
                    [176,176,"Dhanusa","Bateshwor Rural Municipality","बटेश्वर गाउँपालिका",20304],
                    [177,177,"Dhanusa","Chhireshwornath Municipality","क्षिरेश्वरनाथ नगरपालिका",20305],
                    [178,178,"Dhanusa","Laxminiya Rural Municipality","लक्ष्मीनिया गाउँपालिका",20306],
                    [179,179,"Dhanusa","Mithila Bihari Municipality","मिथिला बिहारी नगरपालिका",20307],
                    [180,180,"Dhanusa","Hansapur Municipality","हंसपुर नगरपालिका",20308],
                    [181,181,"Dhanusa","Sabaila Municipality","सबैला नगरपालिका",20309],
                    [182,182,"Dhanusa","Shahidnagar Municipality","शहीदनगर नगरपालिका",20310],
                    [183,183,"Dhanusa","Kamala Municipality","कमला नगरपालिका",20311],
                    [184,184,"Dhanusa","Janak Nandini Rural Municipality","जनक नन्दिनी गाउँपालिका",20312],
                    [185,185,"Dhanusa","Bideha Municipality","बिदेह नगरपालिका",20313],
                    [186,186,"Dhanusa","Aurahi Rural Municipality","औरही गाउँपालिका",20314],
                    [187,187,"Dhanusa","Janakpur Sub-Metropolitian City","जनकपुर उपमहानगरपालिका",20315],
                    [188,188,"Dhanusa","Dhanauji Rural Municipality","धनौजी गाउँपालिका",20316],
                    [189,189,"Dhanusa","Nagarain Municipality","नगराइन नगरपालिका",20317],
                    [190,190,"Dhanusa","Mukhiyapatti Musaharmiya Rural Municipality","मुखियापट्टी मुसहरमिया गाउँपालिका",20318],
                    [191,191,"Mahottari","Bardibas Municipality","बर्दिबास नगरपालिका",20401],
                    [192,192,"Mahottari","Gaushala Municipality","गौशाला नगरपालिका",20402],
                    [193,193,"Mahottari","Sonama Rural Municipality","सोनमा गाउँपालिका",20403],
                    [194,194,"Mahottari","Aurahi Municipality","औरही नगरपालिका",20404],
                    [195,195,"Mahottari","Bhangaha Municipality","भँगाहा नगरपालिका",20405],
                    [196,196,"Mahottari","Loharpatti Municipality","लोहरपट्टी नगरपालिका",20406],
                    [197,197,"Mahottari","Balawa Municipality","बलवा नगरपालिका",20407],
                    [198,198,"Mahottari","Ram Gopalpur Municipality","राम गोपालपुर नगरपालिका",20408],
                    [199,199,"Mahottari","Samsi Rural Municipality","साम्सी गाउँपालिका",20409],
                    [200,200,"Mahottari","Manara Shisawa Municipality","मनरा शिसवा नगरपालिका",20410],
                    [201,201,"Mahottari","Ekadara Rural Municipality","एकडारा गाउँपालिका",20411],
                    [202,202,"Mahottari","Mahottari Rural Municipality","महोत्तरी गाउँपालिका",20412],
                    [203,203,"Mahottari","Pipara Rural Municipality","पिपरा गाउँपालिका",20413],
                    [204,204,"Mahottari","Matihani Municipality","मटिहानी नगरपालिका",20414],
                    [205,205,"Mahottari","Jaleshwor Municipality","जलेश्वर नगरपालिका",20415],
                    [206,206,"Sarlahi","Lalbandi Municipality","लालबन्दी नगरपालिका",20501],
                    [207,207,"Sarlahi","Hariwan Municipality","हरिवन नगरपालिका",20502],
                    [208,208,"Sarlahi","Bagmati Municipality","बागमती नगरपालिका",20503],
                    [209,209,"Sarlahi","Barahathawa Municipality","बरहथवा नगरपालिका",20504],
                    [210,210,"Sarlahi","Haripur Municipality","हरिपुर नगरपालिका",20505],
                    [211,211,"Sarlahi","Ishworpur Municipality","ईश्वरपुर नगरपालिका",20506],
                    [212,212,"Sarlahi","Haripurwa Municipality","हरिपुर्वा नगरपालिका",20507],
                    [213,213,"Sarlahi","Parsa Rural Municipality","पर्सा गाउँपालिका",20508],
                    [214,214,"Sarlahi","Brahmapuri Rural Municipality","ब्रह्मपुरी गाउँपालिका",20509],
                    [215,215,"Sarlahi","Chandranagar Rural Municipality","चन्द्रनगर गाउँपालिका",20510],
                    [216,216,"Sarlahi","Kabilashi Municipality","कविलासी नगरपालिका",20511],
                    [217,217,"Sarlahi","Chakraghatta Rural Municipality","चक्रघट्टा गाउँपालिका",20512],
                    [218,218,"Sarlahi","Basbariya Rural Municipality","बसबरिया गाउँपालिका",20513],
                    [219,219,"Sarlahi","Dhanakaul Rural Municipality","धनकौल गाउँपालिका",20514],
                    [220,220,"Sarlahi","Ramnagar Rural Municipality","रामनगर गाउँपालिका",20515],
                    [221,221,"Sarlahi","Balara Municipality","बलरा नगरपालिका",20516],
                    [222,222,"Sarlahi","Godaita Municipality","गोडैटा नगरपालिका",20517],
                    [223,223,"Sarlahi","Bishnu Rural Municipality","विष्णु गाउँपालिका",20518],
                    [224,224,"Sarlahi","Kaudena Rural Municipality","कौडेना गाउँपालिका",20519],
                    [225,225,"Sarlahi","Malangawa Municipality","मलंगवा नगरपालिका",20520],
                    [226,226,"Rautahat","Chandrapur Municipality","चन्द्रपुर नगरपालिका",20601],
                    [227,227,"Rautahat","Gujara Municipality","गुजरा नगरपालिका",20602],
                    [228,228,"Rautahat","Phatuwa Bijayapur Municipality","फतुवा बिजयपुर नगरपालिका",20603],
                    [229,229,"Rautahat","Katahariya Municipality","कटहरिया नगरपालिका",20604],
                    [230,230,"Rautahat","Brindaban Municipality","बृन्दावन नगरपालिका",20605],
                    [231,231,"Rautahat","Gadhimai Municipality","गढीमाई नगरपालिका",20606],
                    [232,232,"Rautahat","Madhav Narayan Municipality","माधव नारायण नगरपालिका",20607],
                    [233,233,"Rautahat","Garuda Municipality","गरुडा नगरपालिका",20608],
                    [234,234,"Rautahat","Dewahi Gonahi Municipality","देवाही गोनाही नगरपालिका",20609],
                    [235,235,"Rautahat","Maulapur Municipality","मौलापुर नगरपालिका",20610],
                    [236,236,"Rautahat","Boudhimai Municipality","बौधीमाई नगरपालिका",20611],
                    [237,237,"Rautahat","Paroha Municipality","परोहा नगरपालिका",20612],
                    [238,238,"Rautahat","Rajpur Municipality","राजपुर नगरपालिका",20613],
                    [239,239,"Rautahat","Yamunamai Rural Municipality","यमुनामाई गाउँपालिका",20614],
                    [240,240,"Rautahat","Durga Bhagawati Rural Municipality","दुर्गा भगवती गाउँपालिका",20615],
                    [241,241,"Rautahat","Rajdevi Municipality","राजदेवी नगरपालिका",20616],
                    [242,242,"Rautahat","Gaur Municipality","गौर नगरपालिका",20617],
                    [243,243,"Rautahat","Ishanath Municipality","ईशनाथ नगरपालिका",20618],
                    [244,244,"Bara","Nijagadh Municipality","निजगढ नगरपालिका",20701],
                    [245,245,"Bara","Kolhabi Municipality","कोल्हवी नगरपालिका",20702],
                    [246,246,"Bara","Jitpur Simara Sub-Metropolitian City","जीतपुर सिमरा उपमहानगरपालिका",20703],
                    [247,247,"Bara","Parawanipur Rural Municipality","परवानीपुर गाउँपालिका",20704],
                    [248,248,"Bara","Prasauni Rural Municipality","प्रसौनी गाउँपालिका",20705],
                    [249,249,"Bara","Bishrampur Rural Municipality","विश्रामपुर गाउँपालिका",20706],
                    [250,250,"Bara","Pheta Rural Municipality","फेटा गाउँपालिका",20707],
                    [251,251,"Bara","Kalaiya Sub-Metropolitian City","कलैया उपमहानगरपालिका",20708],
                    [252,252,"Bara","Karaiyamai Rural Municipality","करैयामाई गाउँपालिका",20709],
                    [253,253,"Bara","Baragadhi Rural Municipality","बारागढी गाउँपालिका",20710],
                    [254,254,"Bara","Aadarsha Kotwal Rural Municipality","आदर्श कोटवाल गाउँपालिका",20711],
                    [255,255,"Bara","Simroungadh Municipality","सिम्रौनगढ नगरपालिका",20712],
                    [256,256,"Bara","Pacharauta Municipality","पचरौता नगरपालिका",20713],
                    [257,257,"Bara","Mahagadhimai Municipality","महागढीमाई नगरपालिका",20714],
                    [258,258,"Bara","Devtal Rural Municipality","देवताल गाउँपालिका",20715],
                    [259,259,"Bara","Subarna Rural Municipality","सुवर्ण गाउँपालिका",20716],
                    [260,260,"Parsa","Thori Rural Municipality","ठोरी (सुवर्णपुर) गाउँपालिका",20801],
                    [261,261,"Parsa","Jirabhawani Rural Municipality","जिराभवानी गाउँपालिका",20802],
                    [262,262,"Parsa","Jagarnathpur Rural Municipality","जगरनाथपुर गाउँपालिका",20803],
                    [263,263,"Parsa","Paterwa Sugauli Rural Municipality","पटेर्वा सुगौली गाउँपालिका",20804],
                    [264,264,"Parsa","Sakhuwa Prasauni Rural Municipality","सखुवा प्रसौनी गाउँपालिका",20805],
                    [265,265,"Parsa","Parsagadhi Municipality","पर्सागढी नगरपालिका",20806],
                    [266,266,"Parsa","Birgunj Metropolitian City","बिरगन्ज महानगरपालिका",20807],
                    [267,267,"Parsa","Bahudarmai Municipality","बहुदरमाई नगरपालिका",20808],
                    [268,268,"Parsa","Pokhariya Municipality","पोखरिया नगरपालिका",20809],
                    [269,269,"Parsa","Kalikamai Rural Municipality","कालिकामाई गाउँपालिका",20810],
                    [270,270,"Parsa","Dhobini Rural Municipality","धोबीनी गाउँपालिका",20811],
                    [271,271,"Parsa","Chhipaharmai Rural Municipality","छिपहरमाई गाउँपालिका",20812],
                    [272,272,"Parsa","Pakaha Mainpur Rural Municipality","पकाहा मैनपुर गाउँपालिका",20813],
                    [273,273,"Parsa","Bindabasini Rural Municipality","बिन्दबासिनी गाउँपालिका",20814],
                    [274,274,"Dolakha","Gaurishankar Rural Municipality","गौरिशंकर गाउँपालिका",30101],
                    [275,275,"Dolakha","Bigu Rural Municipality","बिगु गाउँपालिका",30102],
                    [276,276,"Dolakha","Kalinchowk Rural Municipality","कालिन्चोक गाउँपालिका",30103],
                    [277,277,"Dolakha","Baitedhar Rural Municipality","बैतेधर गाउँपालिका",30104],
                    [278,278,"Dolakha","Jiri Municipality","जिरी नगरपालिका",30105],
                    [279,279,"Dolakha","Tamakoshi Rural Municipality","तामाकोशी गाउँपालिका",30106],
                    [280,280,"Dolakha","Melung Rural Municipality","मेलुङ्ग गाउँपालिका",30107],
                    [281,281,"Dolakha","Shailung Rural Municipality","शैलुड० गाउँपालिका",30108],
                    [282,282,"Dolakha","Bhimeshwor Municipality","भिमेश्वर नगरपालिका",30109],
                    [283,283,"Sindhupalchok","Bhotekoshi Rural Municipality","भोटेकोशी गाउँपालिका",30201],
                    [284,284,"Sindhupalchok","Jugal Rural Municipality","जुगल गाउँपालिका",30202],
                    [285,285,"Sindhupalchok","Panchpokhari Thangpal Rural Municipality","पाँचपोखरी थाड०पाल गाउँपालिका",30203],
                    [286,286,"Sindhupalchok","Helambu Rural Municipality","हेलम्बु गाउँपालिका",30204],
                    [287,287,"Sindhupalchok","Melanchi Municipality","मेलम्ची नगरपालिका",30205],
                    [288,288,"Sindhupalchok","Indrawoti Rural Municipality","ईन्द्रावती गाउँपालिका",30206],
                    [289,289,"Sindhupalchok","Choutara Sangachowkgadhi Municipality","चौतारा साँगाचोकगढी नगरपालिका",30207],
                    [290,290,"Sindhupalchok","Balephi Rural Municipality","बलेफी गाउँपालिका",30208],
                    [291,291,"Sindhupalchok","Bahrabise Municipality","बाह्रबिसे नगरपालिका",30209],
                    [292,292,"Sindhupalchok","Tripurasundari Rural Municipality","त्रिपुरासुन्दरी गाउँपालिका",30210],
                    [293,293,"Sindhupalchok","Lisankhu Pakhar Rural Municipality","लिसंखु पाखर गाउँपालिका",30211],
                    [294,294,"Sindhupalchok","Sunkoshi Rural Municipality","सुनकोशी गाउँपालिका",30212],
                    [295,295,"Rasuwa","Gosaikunda Rural Municipality","गोसाईकुण्ड गाउँपालिका",30301],
                    [296,296,"Rasuwa","Parbatikunda Rural Municipality","पार्वतीकुण्ड गाउँपालिका",30302],
                    [297,297,"Rasuwa","Uttargaya Rural Municipality","उत्तरगया गाउँपालिका",30303],
                    [298,298,"Rasuwa","Kalika Rural Municipality","कालिका गाउँपालिका",30304],
                    [299,299,"Rasuwa","Naukunda Rural Municipality","नौकुण्ड गाउँपालिका",30305],
                    [300,300,"Dhading","Rubi Valley Rural Municipality","रुबी भ्याली गाउँपालिका",30401],
                    [301,301,"Dhading","Khaniyabas Rural Municipality","खनियाबास गाउँपालिका",30402],
                    [302,302,"Dhading","Ganga Jamuna Rural Municipality","गंङ्गा जमुना गाउँपालिका",30403],
                    [303,303,"Dhading","Tripurasundari Rural Municipality","त्रिपुरासुन्दरी गाउँपालिका",30404],
                    [304,304,"Dhading","Netrawati Rural Municipality","नेत्रावती गाउँपालिका",30405],
                    [305,305,"Dhading","Nilkhantha Municipality","नीलकण्ठ नगरपालिका",30406],
                    [306,306,"Dhading","Jwalamukhi Rural Municipality","ज्वालामुखी गाउँपालिका",30407],
                    [307,307,"Dhading","Siddhalek Rural Municipality","सिद्धलेक गाउँपालिका",30408],
                    [308,308,"Dhading","Benighat Rorang Rural Municipality","बेनीघाट रोराङ्ग गाउँपालिका",30409],
                    [309,309,"Dhading","Gajuri Rural Municipality","गजुरी गाउँपालिका",30410],
                    [310,310,"Dhading","Galchhi Rural Municipality","गल्छी गाउँपालिका",30411],
                    [311,311,"Dhading","Thakre Rural Municipality","थाक्रे गाउँपालिका",30412],
                    [312,312,"Dhading","Dhunibenshi Municipality","धुनीबेंशी नगरपालिका",30413],
                    [313,313,"Nuwakot","Dupcheshwor Rural Municipality","दुप्चेश्वर गाउँपालिका",30501],
                    [314,314,"Nuwakot","Tadi Rural Municipality","तादी गाउँपालिका",30502],
                    [315,315,"Nuwakot","Suryagadhi Rural Municipality","सुर्यगढी गाउँपालिका",30503],
                    [316,316,"Nuwakot","Bidur Municipality","बिदुर नगरपालिका",30504],
                    [317,317,"Nuwakot","Kispang Rural Municipality","किस्पाङ्ग गाउँपालिका",30505],
                    [318,318,"Nuwakot","Meghang Rural Municipality","मेघाङ्ग गाउँपालिका",30506],
                    [319,319,"Nuwakot","Tarakeshwor Rural Municipality","तारकेश्वर गाउँपालिका",30507],
                    [320,320,"Nuwakot","Belkotgadhi Municipality","बेलकोटगढी नगरपालिका",30508],
                    [321,321,"Nuwakot","Likhu Rural Municipality","लिखु गाउँपालिका",30509],
                    [322,322,"Nuwakot","Panchakanya Rural Municipality","पन्चकन्या गाउँपालिका",30510],
                    [323,323,"Nuwakot","Shivapuri Rural Municipality","शिवपुरी गाउँपालिका",30511],
                    [324,324,"Nuwakot","Kakani Rural Municipality","ककनी गाउँपालिका",30512],
                    [325,325,"Kathmandu","Shankharapur Municipality","शंङ्खरापुर नगरपालिका",30601],
                    [326,326,"Kathmandu","Kageshwori Manahara Municipality","कागेश्वरी मनहरा नगरपालिका",30602],
                    [327,327,"Kathmandu","Gokarneshwor Municipality","गोकर्णेश्वर नगरपालिका",30603],
                    [328,328,"Kathmandu","Budhanilkhantha Municipality","बुढानिलकण्ठ नगरपालिका",30604],
                    [329,329,"Kathmandu","Tokha Municipality","टोखा नगरपालिका",30605],
                    [330,330,"Kathmandu","Tarakeshwor Municipality","तारकेश्वर नगरपालिका",30606],
                    [331,331,"Kathmandu","Nagarjun Municipality","नागार्जुन नगरपालिका",30607],
                    [332,332,"Kathmandu","Kathmandu Metropolitian City","काठमाण्डौ महानगरपालिका",30608],
                    [333,333,"Kathmandu","Kirtipur Municipality","किर्तिपुर नगरपालिका",30609],
                    [334,334,"Kathmandu","Chandragiri Municipality","चन्द्रागिरी नगरपालिका",30610],
                    [335,335,"Kathmandu","Dakshinkali Municipality","दक्षिणकाली नगरपालिका",30611],
                    [336,336,"Bhaktapur","Changunarayan Municipality","चाँगुनारायण नगरपालिका",30701],
                    [337,337,"Bhaktapur","Bhaktapur Municipality","भक्तपुर नगरपालिका",30702],
                    [338,338,"Bhaktapur","Madhyapur Thimi Municipality","मध्यपुर थिमी नगरपालिका",30703],
                    [339,339,"Bhaktapur","Suryabinayak Municipality","सूर्यविनायक नगरपालिका",30704],
                    [340,340,"Lalitpur","Mahalaxmi Municipality","महालक्ष्मी नगरपालिका",30801],
                    [341,341,"Lalitpur","Lalitpur Metropolitian City","ललितपुर महानगरपालिका",30802],
                    [342,342,"Lalitpur","Godawari Municipality","गोदावरी नगरपालिका",30803],
                    [343,343,"Lalitpur","Konjyosom Rural Municipality","कोन्ज्योसोम गाउँपालिका",30804],
                    [344,344,"Lalitpur","Mahankal Rural Municipality","महाङ्काल गाउँपालिका",30805],
                    [345,345,"Lalitpur","Bagmati Rural Municipality","बाग्मती गाउँपालिका",30806],
                    [346,346,"Kavrepalanchok","Chauri Deurali Rural Municipality","चौरीदेउराली गाउँपालिका",30901],
                    [347,347,"Kavrepalanchok","Bhumlu Rural Municipality","भुम्लु गाउँपालिका",30902],
                    [348,348,"Kavrepalanchok","Mandan Deupur Municipality","मण्डन देउपुर नगरपालिका",30903],
                    [349,349,"Kavrepalanchok","Banepa Municipality","बनेपा नगरपालिका",30904],
                    [350,350,"Kavrepalanchok","Dhulikhel Municipality","धुलिखेल नगरपालिका",30905],
                    [351,351,"Kavrepalanchok","Panchkhal Municipality","पाँचखाल नगरपालिका",30906],
                    [352,352,"Kavrepalanchok","Temal Rural Municipality","तेमाल गाउँपालिका",30907],
                    [353,353,"Kavrepalanchok","Namobuddha Municipality","नमोबुद्ध नगरपालिका",30908],
                    [354,354,"Kavrepalanchok","Panauti Municipality","पनौती नगरपालिका",30909],
                    [355,355,"Kavrepalanchok","Bethanchowk Rural Municipality","बेथानचोक गाउँपालिका",30910],
                    [356,356,"Kavrepalanchok","Roshi Rural Municipality","रोशी गाउँपालिका",30911],
                    [357,357,"Kavrepalanchok","Mahabharat Rural Municipality","महाभारत गाउँपालिका",30912],
                    [358,358,"Kavrepalanchok","Khanikhola Rural Municipality","खानीखोला गाउँपालिका",30913],
                    [359,359,"Ramechhap","Umakunda Rural Municipality","उमाकुण्ड गाउँपालिका",31001],
                    [360,360,"Ramechhap","Gokulganga Rural Municipality","गोकुलगङ्गा गाउँपालिका",31002],
                    [361,361,"Ramechhap","Likhu Rural Municipality","लिखु गाउँपालिका",31003],
                    [362,362,"Ramechhap","Ramechhap Municipality","रामेछाप नगरपालिका",31004],
                    [363,363,"Ramechhap","Manthali  Municipality","मन्थली नगरपालिका",31005],
                    [364,364,"Ramechhap","Khandadevi Rural Municipality","खाँडादेवी गाउँपालिका",31006],
                    [365,365,"Ramechhap","Doramba Rural Municipality","दोरम्बा गाउँपालिका",31007],
                    [366,366,"Ramechhap","Sunapati Rural Municipality","सुनापती गाउँपालिका",31008],
                    [367,367,"Sindhuli","Dudhouli Municipality","दुधौली नगरपालिका",31101],
                    [368,368,"Sindhuli","Phikkal Rural Municipality","फिक्कल गाउँपालिका",31102],
                    [369,369,"Sindhuli","Tinpatan Rural Municipality","तीनपाटन गाउँपालिका",31103],
                    [370,370,"Sindhuli","Golanjor Rural Municipality","गोलन्जोर गाउँपालिका",31104],
                    [371,371,"Sindhuli","Kamalamai Municipality","कमलामाई नगरपालिका",31105],
                    [372,372,"Sindhuli","Sunkoshi Rural Municipality","सुनकोशी गाउँपालिका",31106],
                    [373,373,"Sindhuli","Ghyanglekha Rural Municipality","ध्याङलेख गाउँपालिका",31107],
                    [374,374,"Sindhuli","Marin Rural Municipality","मरिण गाउँपालिका",31108],
                    [375,375,"Sindhuli","Hariharpurgaghi Rural Municipality","हरिहरपुरगढी गाउँपालिका",31109],
                    [376,376,"Makwanpur","Indrasarowar Rural Municipality","ईन्द्रसरोवर गाउँपालिका",31201],
                    [377,377,"Makwanpur","Thaha Municipality","थाहा नगरपालिका",31202],
                    [378,378,"Makwanpur","Kailash Rural Municipality","कैलाश गाउँपालिका",31203],
                    [379,379,"Makwanpur","Raksirang Rural Municipality","राक्सिराङ्ग गाउँपालिका",31204],
                    [380,380,"Makwanpur","Manahari Rural Municipality","मनहरी गाउँपालिका",31205],
                    [381,381,"Makwanpur","Hetauda Sub-Metropolitian City","हेटौडा उपमहानगरपालिका",31206],
                    [382,382,"Makwanpur","Bhimphedi Rural Municipality","भिमफेदी गाउँपालिका",31207],
                    [383,383,"Makwanpur","Makawanpurgadhi Rural Municipality","मकवानपुरगढी गाउँपालिका",31208],
                    [384,384,"Makwanpur","Bakaiya Rural Municipality","बकैया गाउँपालिका",31209],
                    [385,385,"Makwanpur","Bagmati Rural Municipality","बाग्मती गाउँपालिका",31210],
                    [386,386,"Chitawan","Rapti Municipality","राप्ती नगरपालिका",31301],
                    [387,387,"Chitawan","Kalika Municipality","कालिका नगरपालिका",31302],
                    [388,388,"Chitawan","Ichchha Kamana Rural Municipality","इच्छाकामना गाउँपालिका",31303],
                    [389,389,"Chitawan","Bharatpur Metropolitian City","भरतपुर महानगरपालिका",31304],
                    [390,390,"Chitawan","Ratnanagar Municipality","रत्ननगर नगरपालिका",31305],
                    [391,391,"Chitawan","Khairahani Municipality","खैरहनी नगरपालिका",31306],
                    [392,392,"Chitawan","Madi Municipality","माडी नगरपालिका",31307],
                    [393,393,"Gorkha","Chumanubri Rural Municipality","चुमनुब्री गाउँपालिका",40101],
                    [394,394,"Gorkha","Ajirkot Rural Municipality","अजिरकोट गाउँपालिका",40102],
                    [395,395,"Gorkha","Sulikot Rural Municipality","सुलीकोट गाउँपालिका",40103],
                    [396,396,"Gorkha","Dharche Rural Municipality","धार्चे गाउँपालिका",40104],
                    [397,397,"Gorkha","Aarughat Rural Municipality","आरुघाट गाउँपालिका",40105],
                    [398,398,"Gorkha","Bhimsen Rural Municipality","भिमसेन गाउँपालिका",40106],
                    [399,399,"Gorkha","Siranchowk Rural Municipality","सिरानचोक गाउँपालिका",40107],
                    [400,400,"Gorkha","Palungtar Municipality","पालुङ्गटार नगरपालिका",40108],
                    [401,401,"Gorkha","Gorkha Municipality","गोरखा नगरपालिका",40109],
                    [402,402,"Gorkha","Shahid Lakhan Rural Municipality","शहीद लखन गाउँपालिका",40110],
                    [403,403,"Gorkha","Gandaki Rural Municipality","गण्डकी गाउँपालिका",40111],
                    [404,404,"Manang","Naraphu Rural Municipality","नारफु गाउँपालिका",40201],
                    [405,405,"Manang","Neshang Rural Municipality","नेस्याङ गाउँपालिका",40202],
                    [406,406,"Manang","Chame Rural Municipality","चामे गाउँपालिका",40203],
                    [407,407,"Manang","Nashong Rural Municipality","नाशोङ गाउँपालिका",40204],
                    [408,408,"Mustang","Dalome Rural Municipality","दालोमे गाउँपालिका",40301],
                    [409,409,"Mustang","Gharpajhong Rural Municipality","घरपझोङ गाउँपालिका",40302],
                    [410,410,"Mustang","Bahragaun Muktikshetra Rural Municipality","बाह्रगाउँ मुक्तिक्षेत्र गाउँपालिका",40303],
                    [411,411,"Mustang","Lomanthang Rural Municipality","लोमन्थाङ गाउँपालिका",40304],
                    [412,412,"Mustang","Thasang Rural Municipality","थासाङ गाउँपालिका",40305],
                    [413,413,"Myagdi","Annapurna Rural Municipality","अन्नपूर्ण गाउँपालिका",40401],
                    [414,414,"Myagdi","Raghuganga Rural Municipality","रघुगंगा गाउँपालिका",40402],
                    [415,415,"Myagdi","Dhawalagiri Rural Municipality","धवलागिरी गाउँपालिका",40403],
                    [416,416,"Myagdi","Malika Rural Municipality","मालिका गाउँपालिका",40404],
                    [417,417,"Myagdi","Mangala Rural Municipality","मंगला गाउँपालिका",40405],
                    [418,418,"Myagdi","Beni Municipality","बेनी नगरपालिका",40406],
                    [419,419,"Kaski","Madi Rural Municipality","मादी गाउँपालिका",40501],
                    [420,420,"Kaski","Machhapuchchhre Rural Municipality","माछापुच्छ्र्े गाउँपालिका",40502],
                    [421,421,"Kaski","Annapurna Rural Municipality","अन्नपूर्ण गाउँपालिका",40503],
                    [422,422,"Kaski","Pokhara Lekhnath Metropolitian City","पोखरा लेखनाथ महानगरपालिका",40504],
                    [423,423,"Kaski","Rupa Rural Municipality","रूपा गाउँपालिका",40505],
                    [424,424,"Lamjung","Dordi Rural Municipality","दोर्दी गाउँपालिका",40601],
                    [425,425,"Lamjung","Marshyangdi Rural Municipality","मस्र्याङ्गदी गाउँपालिका",40602],
                    [426,426,"Lamjung","Kwhola Sothar Rural Municipality","क्ब्होलासोथार गाउँपालिका",40603],
                    [427,427,"Lamjung","Madhya Nepal Municipality","मध्यनेपाल नगरपालिका",40604],
                    [428,428,"Lamjung","Bensi Shahar Municipality","बेंसीशहर नगरापालिका",40605],
                    [429,429,"Lamjung","Sundarbazar Municipality","सुन्दरबजार नगरपालिका",40606],
                    [430,430,"Lamjung","Rainas Municipality","राईनास नगरपालिका",40607],
                    [431,431,"Lamjung","Dudhapokhari Rural Municipality","दुधपोखरी गाउँपालिका",40608],
                    [432,432,"Tanahu","Bhanu Municipality","भानु नगरपालिका",40701],
                    [433,433,"Tanahu","Byas Municipality","ब्यास नगरपालिका",40702],
                    [434,434,"Tanahu","Myagde Rural Municipality","म्याग्दे गाउँपालिका",40703],
                    [435,435,"Tanahu","Shuklagandaki Municipality","शुक्लागण्डकी नगरपालिका",40704],
                    [436,436,"Tanahu","Bhimad Municipality","भिमाद नगरपालिका",40705],
                    [437,437,"Tanahu","Ghiring Rural Municipality","घिरिङ्ग गाउँपालिका",40706],
                    [438,438,"Tanahu","Rhishing Rural Municipality","ऋषिङ्ग गाउँपालिका",40707],
                    [439,439,"Tanahu","Devghat Rural Municipality","देवघाट गाउँपालिका",40708],
                    [440,440,"Tanahu","Bandipur Rural Municipality","बन्दिपुर गाउँपालिका",40709],
                    [441,441,"Tanahu","Aanbu Khaireni Rural Municipality","आँबुखैरेनी गाउँपालिका",40710],
                    [442,442,"Nawalparasi East","Gaidakot Municipality","गैडाकोट नगरपालिका",40801],
                    [443,443,"Nawalparasi East","Bulingtar Rural Municipality","बुलिङ्गटार गाउँपालिका",40802],
                    [444,444,"Nawalparasi East","Bungdikali Rural Municipality","बुङ्दीकाली गाउँपालिका",40803],
                    [445,445,"Nawalparasi East","Hupsekot Rural Municipality","हुप्सेकोट गाउँपालिका",40804],
                    [446,446,"Nawalparasi East","Devchuli Municipality","देवचुली नगरपालिका",40805],
                    [447,447,"Nawalparasi East","Kawasoti Municipality","कावासोती नगरपालिका",40806],
                    [448,448,"Nawalparasi East","Madhya Bindu Municipality","मध्यबिन्दु नगरपालिका",40807],
                    [449,449,"Nawalparasi East","Binayi Tribeni Rural Municipality","बिनयी त्रिवेणी गाउँपालिका",40808],
                    [450,450,"Syangja","Putalibazar Municipality","पुतलीबजार नगरपालिका",40901],
                    [451,451,"Syangja","Phedikhola Rural Municipality","फेदीखोला गाउँपालिका",40902],
                    [452,452,"Syangja","Aandhikhola Rural Municipality","आँधिखोला गाउँपालिका",40903],
                    [453,453,"Syangja","Arjun Choupari Rural Municipality","अर्जुनचौपारी गाउँपालिका",40904],
                    [454,454,"Syangja","Bhirkot Municipaity","भीरकोट नगरपालिका",40905],
                    [455,455,"Syangja","Biruwa Rural Municipality","बिरुवा गाउँपालिका",40906],
                    [456,456,"Syangja","Harinas Rural Municipality","हरिनास गाउँपालिका",40907],
                    [457,457,"Syangja","Chapakot Municipality","चापाकोट नगरपालिका",40908],
                    [458,458,"Syangja","Walling Municipality","वालिङ्ग नगरपालिका",40909],
                    [459,459,"Syangja","Galyang Municipality","गल्याङ नगरपालिका",40910],
                    [460,460,"Syangja","Kaligandaki Rural Municipality","कालीगण्डकी गाउँपालिका",40911],
                    [461,461,"Parbat","Modi Rural Municipality","मोदी गाउँपालिका",41001],
                    [462,462,"Parbat","Jaljala Rural Municipality","जलजला गाउँपालिका",41002],
                    [463,463,"Parbat","Kushma Municipality","कुश्मा नगरपालिका",41003],
                    [464,464,"Parbat","Phalebas Municipality","फलेबास नगरपालिका",41004],
                    [465,465,"Parbat","Mahashila Rural Municipality","महाशिला गाउँपालिका",41005],
                    [466,466,"Parbat","Bihadi Rural Municipality","बिहादी गाउँपालिका",41006],
                    [467,467,"Parbat","Paiyu Rural Municipality","पैयुं गाउँपालिका",41007],
                    [468,468,"Baglung","Baglung Municipality","बाग्लुङ्ग नगरपालिका",41101],
                    [469,469,"Baglung","Kathekhola Rural Municipality","काठेखोला गाउँपालिका",41102],
                    [470,470,"Baglung","Tarakhola Rural Municipality","ताराखोला गाउँपालिका",41103],
                    [471,471,"Baglung","Tamankhola Rural Municipality","तमानखोला गाउँपालिका",41104],
                    [472,472,"Baglung","Dhorpatan Municipality","ढोरपाटन नगरपालिका",41105],
                    [473,473,"Baglung","Nisikhola Rural Municipality","निसीखोला गाउँपालिका",41106],
                    [474,474,"Baglung","Badigad Rural Municipality","बडिगाड गाउँपालिका",41107],
                    [475,475,"Baglung","Galkot Municipality","गल्कोट नगरपालिका",41108],
                    [476,476,"Baglung","Bareng Rural Municipality","बरेङ गाउँपालिका",41109],
                    [477,477,"Baglung","Jaimuni Municipality","जैमुनी नगरपालिका",41110],
                    [478,478,"Rukum East ","Putha Uttanganga Rural Municipality","पुथा उत्तरगंगा गाउँपालिका",50101],
                    [479,479,"Rukum East ","Sisne Rural Municipality","सिस्ने गाउँपालिका",50102],
                    [480,480,"Rukum East ","Bhoome Rural Municipality","भूमे गाउँपालिका",50103],
                    [481,481,"Rolpa","Sunchhahari Rural Municipality","सुनछहरी गाउँपालिका",50201],
                    [482,482,"Rolpa","Thawang Rural Municipality","थबाङ्ग गाउँपालिका",50202],
                    [483,483,"Rolpa","Duikholi Rural Municipality","दुईखोली गाउँपालिका",50203],
                    [484,484,"Rolpa","Sukidaha Rural Municipality","सुकिदह गाउँपालिका",50204],
                    [485,485,"Rolpa","Madi Rural Municipality","माडी गाउँपालिका",50205],
                    [486,486,"Rolpa","Tribeni Rural Municipality","त्रिवेणी गाउँपालिका",50206],
                    [487,487,"Rolpa","Rolpa Municipality","रोल्पा नगरपालिका",50207],
                    [488,488,"Rolpa","Runtigadhi Rural Municipality","रुन्टीगढी गाउँपालिका",50208],
                    [489,489,"Rolpa","Subarnabati Rural Municipality","सुवर्णावती गाउँपालिका",50209],
                    [490,490,"Rolpa","Lungri Rural Municipality","लुङ्ग्री गाउँपालिका",50210],
                    [491,491,"Pyuthan","Gaumukhi Rural Municipality","गौमुखी गाउँपालिका",50301],
                    [492,492,"Pyuthan","Naubahini Rural Municipality","नौबहिनी गाउँपालिका",50302],
                    [493,493,"Pyuthan","Jhimaruk Rural Municipality","झिमरुक गाउँपालिका",50303],
                    [494,494,"Pyuthan","Pyuthan Municipality","प्यूठान नगरपालिका",50304],
                    [495,495,"Pyuthan","Sworgadwari Municipality","स्वर्गद्धारी नगरपालिका",50305],
                    [496,496,"Pyuthan","Mandavi Rural Municipality","माण्डवी गाउँपालिका",50306],
                    [497,497,"Pyuthan","Mallarani Rural Municipality","मल्लरानी गाउँपालिका",50307],
                    [498,498,"Pyuthan","Aairawati Rural Municipality","ऐरावती गाउँपालिका",50308],
                    [499,499,"Pyuthan","Sarumarani Rural Municipality","सरुमारानी गाउँपालिका",50309],
                    [500,500,"Gulmi","Kali Gandaki Rural Municipality","कालिगण्डकी गाउँपालिका",50401],
                    [501,501,"Gulmi","Satyawoti Rural Municipality","सत्यवती गाउँपालिका",50402],
                    [502,502,"Gulmi","Chandrakot Rural Municipality","चन्द्रकोट गाउँपालिका",50403],
                    [503,503,"Gulmi","Musikot Municipality","मुसिकोट नगरपालिका",50404],
                    [504,504,"Gulmi","Isma Rural Municipality","ईस्मा गाउँपालिका",50405],
                    [505,505,"Gulmi","Malika Rural Municipality","मालिका गाउँपालिका",50406],
                    [506,506,"Gulmi","Madane Rural Municipality","मदाने गाउँपालिका",50407],
                    [507,507,"Gulmi","Dhurkot Rural Municipality","धुर्कोट गाउँपालिका",50408],
                    [508,508,"Gulmi","Resunga Municipality","रेसुङ्गा नगरपालिका",50409],
                    [509,509,"Gulmi","Gulmi Durbar Gaunpaika","गुल्मी दरबार गाउँपालिका",50410],
                    [510,510,"Gulmi","Chhatrakot Rural Municipality","छत्रकोट गाउँपालिका",50411],
                    [511,511,"Gulmi","Ruru Rural Municipality","रूरू गाउँपालिका",50412],
                    [512,512,"Arghakhanchi","Chhatradev Rural Municipality","छत्रदेव गाउँपालिका",50501],
                    [513,513,"Arghakhanchi","Malarani Rural Municipality","मालारानी गाउँपालिका",50502],
                    [514,514,"Arghakhanchi","Bhumikasthan Municipality","भुमिकास्थान नगरपालिका",50503],
                    [515,515,"Arghakhanchi","Sandhikharka Municipality","सन्धिखर्क नगरपालिका",50504],
                    [516,516,"Arghakhanchi","Panini Rural Municipality","पाणिनी गाउँपालिका",50505],
                    [517,517,"Arghakhanchi","Shitaganga Municipality","शितगंगा नगरपालिका",50506],
                    [518,518,"Palpa","Rampur Municipality","रामपुर नगरपालिका",50601],
                    [519,519,"Palpa","Purbakhola Rural Municipality","पुर्वखोला गाउँपालिका",50602],
                    [520,520,"Palpa","Rambha Rural Municipality","रम्भा गाउँपालिका",50603],
                    [521,521,"Palpa","Baganaskali Rural Municipality","बगनासकाली गाउँपालिका",50604],
                    [522,522,"Palpa","Tansen Municipality","तानसेन नगरपालिका",50605],
                    [523,523,"Palpa","Ribdikot Rural Municipality","रिब्दीकोट गाउँपालिका",50606],
                    [524,524,"Palpa","Rainadevi Chhahara Rural Municipality","रैनादेवी छहरा गाउँपालिका",50607],
                    [525,525,"Palpa","Tinau Rural Municipality","तिनाउ गाउँपालिका",50608],
                    [526,526,"Palpa","Mathagadhi Rural Municipality","माथागढी गाउँपालिका",50609],
                    [527,527,"Palpa","Nisdi Rural Municipality","निस्दी गाउँपालिका",50610],
                    [528,528,"Nawalparasi West","Bardaghat Municipality","बर्दघाट नगरपालिका",50701],
                    [529,529,"Nawalparasi West","Sunawal Municipality","सुनवल नगरपालिका",50702],
                    [530,530,"Nawalparasi West","Ramgram Municipality","रामग्राम नगरपालिका",50703],
                    [531,531,"Nawalparasi West","Palhinandan Rural Municipality","पाल्हीनन्दन गाउँपालिका",50704],
                    [532,532,"Nawalparasi West","Sarawal Rural Municipality","सरावल गाउँपालिका",50705],
                    [533,533,"Nawalparasi West","Pratapapur Rural Municipality","प्रतापपुर गाउँपालिका",50706],
                    [534,534,"Nawalparasi West","Susta Rural Municipality","सुस्ता गाउँपालिका",50707],
                    [535,535,"Rupandehi","Devdaha Municipality","देबदह नगरपालिका",50801],
                    [536,536,"Rupandehi","Butwal Sub-Metropolitian City","बुटवल उपमहानगरपालिका",50802],
                    [537,537,"Rupandehi","Sainamaina Municipality","सैनामैना नगरपालिका",50803],
                    [538,538,"Rupandehi","Kanchan Rural Municipality","कन्चन गाउँपालिका",50804],
                    [539,539,"Rupandehi","Gaidahawa Rural Municipality","गैडहवा गाउँपालिका",50805],
                    [540,540,"Rupandehi","Suddhodhan Rural Municipality","सुद्धोधन गाउँपालिका",50806],
                    [541,541,"Rupandehi","Siyari Rural Municipality","सियारी गाउँपालिका",50807],
                    [542,542,"Rupandehi","Tilottama Municipality","तिलोत्तमा नगरापालिका",50808],
                    [543,543,"Rupandehi","Om Satiya Rural Municipality","ओमसतिया गाउँपालिका",50809],
                    [544,544,"Rupandehi","Rohini Rural Municipality","रोहिणी गाउँपालिका",50810],
                    [545,545,"Rupandehi","Siddharthanagar Municipality","सिद्धार्थनगर नगरपालिका",50811],
                    [546,546,"Rupandehi","Mayadevi Rural Municipality","मायादेवी गाउँपालिका",50812],
                    [547,547,"Rupandehi","Lumbini Sanskritik Municipality","लुम्बिनी साँस्कृतिक नगरपालिका",50813],
                    [548,548,"Rupandehi","Kotahimai Rural Municipality","कोटहीमाई गाउँपालिका",50814],
                    [549,549,"Rupandehi","Sammarimai Rural Municipality","सम्मरीमाई गाउँपालिका",50815],
                    [550,550,"Rupandehi","Marchawari Rural Municipality","मर्चवारी गाउँपालिका",50816],
                    [551,551,"Kapilbastu","Banganga Municipality","बाणगंगा नगरपालिका",50901],
                    [552,552,"Kapilbastu","Buddhabhumi Municipality","बुद्धभूमी नगरपालिका",50902],
                    [553,553,"Kapilbastu","Shivaraj Municipality","शिवराज नगरपालिका",50903],
                    [554,554,"Kapilbastu","Bijayanagar Rural Municipality","बिजयनगर गाउँपालिका",50904],
                    [555,555,"Kapilbastu","Krishnanagar Municipality","कृष्णनगर नगरपालिका",50905],
                    [556,556,"Kapilbastu","Maharajganj Municipality","महाराजगन्ज नगरपालिका",50906],
                    [557,557,"Kapilbastu","Kapilbastu Municipality","कपिलबस्तु नगरपालिका",50907],
                    [558,558,"Kapilbastu","Yasodhara Rural Municipality","यसोधरा गाउँपालिका",50908],
                    [559,559,"Kapilbastu","Mayadevi Rural Municipality","मायादेवी गाउँपालिका",50909],
                    [560,560,"Kapilbastu","Shuddhodhan Rural Municipality","शुद्धोधन गाउँपालिका",50910],
                    [561,561,"Dang","Bangalachuli Rural Municipality","बंगलाचुली गाउँपालिका",51001],
                    [562,562,"Dang","Ghorahi Sub-Metropolitian City","घोराही उपमहानगरपालिका",51002],
                    [563,563,"Dang","Tulsipur Sub-Metropolitian City","तुल्सीपुर उपमहानगरपालिका",51003],
                    [564,564,"Dang","Shantinagar Rural Municipality","शान्तिनगर गाउँपालिका",51004],
                    [565,565,"Dang","Babai Rural Municipality","बबई गाउँपालिका",51005],
                    [566,566,"Dang","Dangisharan Rural Municipality","दंगीशरण गाउँपालिका",51006],
                    [567,567,"Dang","Lamahi Municipality","लमही नगरपालिका",51007],
                    [568,568,"Dang","Rapti Rural Municipality","राप्ती गाउँपालिका",51008],
                    [569,569,"Dang","Gadhawa Rural Municipality","गढवा गाउँपालिका",51009],
                    [570,570,"Dang","Rajpur Rural Municipality","राजपुर गाउँपालिका",51010],
                    [571,571,"Banke","Rapti Sonari Rural Municipality","राप्ती सोनारी गाउँपालिका",51101],
                    [572,572,"Banke","Kohalpur Municipality","कोहलपुर नगरपालिका",51102],
                    [573,573,"Banke","Baijanath Rural Municipality","बैजनाथ गाउँपालिका",51103],
                    [574,574,"Banke","Khajura Rural Municipality","खजुरा गाउँपालिका",51104],
                    [575,575,"Banke","Janaki Rural Municipality","जानकी गाउँपालिका",51105],
                    [576,576,"Banke","Nepalganj Sub-Metropolitian City","नेपालगञ्ज उपमहानगरपालिका",51106],
                    [577,577,"Banke","Duduwa Rural Municipality","डुडुवा गाउँपालिका",51107],
                    [578,578,"Banke","Narainapur Rural Municipality","नरैनापुर गाउँपालिका",51108],
                    [579,579,"Bardiya","Bansgadhi Municipality","बाँसगढी नगरपालिका",51201],
                    [580,580,"Bardiya","Barbardiya Municipality","बारबर्दिया नगरपालिका",51202],
                    [581,581,"Bardiya","Thakurbaba Municipality","ठाकुरबाबा नगरपालिका",51203],
                    [582,582,"Bardiya","Geruwa Rural Municipality","गेरुवा गाउँपालिका",51204],
                    [583,583,"Bardiya","Rajapur Municipality","राजापुर नगरपालिका",51205],
                    [584,584,"Bardiya","Madhuwan Municipality","मधुवन नगरपालिका",51206],
                    [585,585,"Bardiya","Gulariya Municipality","गुलरीया नगरपालिका",51207],
                    [586,586,"Bardiya","Badhaiyatal Rural Municipality","बढैयाताल गाउँपालिका",51208],
                    [587,587,"Dolpa","Dolpo Buddha Rural Municipality","डोल्पो बुद्ध गाउँपालिका",60101],
                    [588,588,"Dolpa","Shey Phoksundo Rural Municipality","शे फोक्सुण्डो गाउँपालिका",60102],
                    [589,589,"Dolpa","Jagadulla Rural Municipality","जगदुल्ला गाउँपालिका",60103],
                    [590,590,"Dolpa","Mudkechula Rural Municipality","मुड्केचुला गाउँपालिका",60104],
                    [591,591,"Dolpa","Tripurasundari Municipality","त्रिपुरासुन्दरी नगरपालिका",60105],
                    [592,592,"Dolpa","Thulibheri Municipality","ठुलीभेरी नगरपालिका",60106],
                    [593,593,"Dolpa","Kaike Rural Municipality","काइके गाउँपालिका",60107],
                    [594,594,"Dolpa","Chharka Tangsong Rural Municipality","छार्का ताङसोङ गाउँपालिका",60108],
                    [595,595,"Mugu","Mugumakarmarog Rural Municipality","मुगुमकार्मारोग गाउँपालिका",60201],
                    [596,596,"Mugu","Chhayanath Rara Municipality","छायाँनाथ रारा नगरपालिका",60202],
                    [597,597,"Mugu","Soru Rural Municipality","सोरु गाउँपालिका",60203],
                    [598,598,"Mugu","Khatyad Rural Municipality","खत्याड गाउँपालिका",60204],
                    [599,599,"Humla","Chankheli Rural Municipality","चंखेली गाउँपालिका",60301],
                    [600,600,"Humla","Kharpunath Rural Municipality","खार्पुनाथ गाउँपालिका",60302],
                    [601,601,"Humla","Simkot Rural Municipality","सिमकोट गाउँपालिका",60303],
                    [602,602,"Humla","Namkha Rural Municipality","नाम्खा गाउँपालिका",60304],
                    [603,603,"Humla","Sarkegad Rural Municipality","सर्केगाड गाउँपालिका",60305],
                    [604,604,"Humla","Adanchuli Rural Municipality","अदानचुली गाउँपालिका",60306],
                    [605,605,"Humla","Tanjakot Rural Municipality","ताँजाकोट गाउँपालिका",60307],
                    [606,606,"Jumla","Patarasi Rural Municipality","पातारासी गाउँपालिका",60401],
                    [607,607,"Jumla","Kanaka Sundari Gaun Palika","कनका सुन्दरी गाउँपालिका",60402],
                    [608,608,"Jumla","Sinja Rural Municipality","सिंजा गाउँपालिका",60403],
                    [609,609,"Jumla","Chandannath Municipality","चन्दननाथ नगरपालिका",60404],
                    [610,610,"Jumla","Guthichaur Rural Municipality","गुठिचौर गाउँपालिका",60405],
                    [611,611,"Jumla","Tatopani Rural Municipality","तातोपानी गाउँपालिका",60406],
                    [612,612,"Jumla","Tila Rural Municipality","तिला गाउँपालिका",60407],
                    [613,613,"Jumla","Hima Rural Municipality","हिमा गाउँपालिका",60408],
                    [614,614,"Kalikot","Palata Rural Municipality","पलाता गाउँपालिका",60501],
                    [615,615,"Kalikot","Pachal Jharana Rural Municipality","पचाल झरना गाउँपालिका",60502],
                    [616,616,"Kalikot","Raskot Municipality","रास्कोट नगरपालिका",60503],
                    [617,617,"Kalikot","Sanni Tribeni Rural Municipality","सान्नी त्रिवेणी गाउँपालिका",60504],
                    [618,618,"Kalikot","Naraharinath Rural Municipality","नरहरिनाथ गाउँपालिका",60505],
                    [619,619,"Kalikot","Khandachakra Municipality","खाँडाचक्र नगरपालिका",60506],
                    [620,620,"Kalikot","Tilagupha Municipality","तिलागुफा नगरपालिका",60507],
                    [621,621,"Kalikot","Mahawai Rural Municipality","महावै गाउँपालिका",60508],
                    [622,622,"Kalikot","Kalika Rural Municipality","कालिका गाउँपालिका",60509],
                    [623,623,"Dailekh","Naumule Rural Municipality","नौमुले गाउँपालिका",60601],
                    [624,624,"Dailekh","Mahabu Rural Municipality","महाबु गाउँपालिका",60602],
                    [625,625,"Dailekh","Bhairabi Rural Municipality","भैरवी गाउँपालिका",60603],
                    [626,626,"Dailekh","Thantikandh Rural Municipality","ठाँटीकाँध गाउँपालिका",60604],
                    [627,627,"Dailekh","Aathbis Municipality","आठबीस नगरपालिका",60605],
                    [628,628,"Dailekh","Chamunda Bindrasaini Municipality","चामुण्डा बिन्द्रासैनी नगरपालिका",60606],
                    [629,629,"Dailekh","Dullu Municipality","दुल्लु नगरपालिका",60607],
                    [630,630,"Dailekh","Narayan Municipality","नारायण नगरपालिका",60608],
                    [631,631,"Dailekh","Bhagawatimai Rural Municipality","भगवतीमाई गाउँपालिका",60609],
                    [632,632,"Dailekh","Dungeshwor Rural Municipality","डुङ्गेश्वर गाउँपालिका",60610],
                    [633,633,"Dailekh","Gurans Rural Municipality","गुराँस गाउँपालिका",60611],
                    [634,634,"Jajarkot","Barekot Rural Municipality","बारेकोट गाउँपालिका",60701],
                    [635,635,"Jajarkot","Kuse Rural Municipality","कुसे गाउँपालिका",60702],
                    [636,636,"Jajarkot","Junichande Rural Municipality","जुनीचाँदे गाउँपालिका",60703],
                    [637,637,"Jajarkot","Chhedagad Municipality","छेडागाड नगरपालिका",60704],
                    [638,638,"Jajarkot","Shivalaya Rural Municipality","शिवालय गाउँपालिका",60705],
                    [639,639,"Jajarkot","Bheri Malika Municipality","भेरीमालिका नगरपालिका",60706],
                    [640,640,"Jajarkot","Tribeni Nalagad Municipality","त्रिवेणी नलगाड नगरपालिका",60707],
                    [641,641,"Rukum West ","Aathabisakot Municipality","आठबिसकोट नगरपालिका",60801],
                    [642,642,"Rukum West ","Sanibheri Rural Municipality","सानीभेरी गाउँपालिका",60802],
                    [643,643,"Rukum West ","Banphikot Rural Municipality","बाँफिकोट गाउँपालिका",60803],
                    [644,644,"Rukum West ","Musikot Municipality","मुसिकोट नगरपालिका",60804],
                    [645,645,"Rukum West ","Tribeni Rural Municipality","त्रिवेणी गाउँपालिका",60805],
                    [646,646,"Rukum West ","Chaurjahari Municipality","चौरजहारी नगरपालिका",60806],
                    [647,647,"Salyan","Darma Rural Municipality","दार्मा गाउँपालिका",60901],
                    [648,648,"Salyan","Kumakh Malika Rural Municipality","कुमाख मालिका गाउँपालिका",60902],
                    [649,649,"Salyan","Banagad Kupinde Municipality","बनगाड कुपिण्डे नगरपालिका",60903],
                    [650,650,"Salyan","Dhorchaur Rural Municipality","ढोरचौर गाउँपालिका",60904],
                    [651,651,"Salyan","Bagachour Municipality","बागचौर नगरपालिका",60905],
                    [652,652,"Salyan","Chhatreshwori Rural Municipality","छत्रेश्वरी गाउँपालिका",60906],
                    [653,653,"Salyan","Sharada Municipality","शारदा नगरपालिका",60907],
                    [654,654,"Salyan","Kalimati Rural Municipality","कालिमाटी गाउँपालिका",60908],
                    [655,655,"Salyan","Tribeni Rural Municipality","त्रिवेणी गाउँपालिका",60909],
                    [656,656,"Salyan","Kapurkot Rural Municipality","कपुरकोट गाउँपालिका",60910],
                    [657,657,"Surkhet","Simta Rural Municipality","सिम्ता गाउँपालिका",61001],
                    [658,658,"Surkhet","Chingad Rural Municipality","चिङ्गगाड गाउँपालिका",61002],
                    [659,659,"Surkhet","Lekabeshi Municipality","लेकबेशी नगरपालिका",61003],
                    [660,660,"Surkhet","Gurbhakot Municipality","गुर्भाकोट नगरपालिका",61004],
                    [661,661,"Surkhet","Bheriganga Municipality","भेरीगंगा नगरपालिका",61005],
                    [662,662,"Surkhet","Birendranagar Municipality","बीरेन्द्रनगर नगरपालिका",61006],
                    [663,663,"Surkhet","Barahatal Rural Municipality","बराहताल गाउँपालिका",61007],
                    [664,664,"Surkhet","Panchapuri Municipality","पञ्चपुरी नगरपालिका",61008],
                    [665,665,"Surkhet","Chaukune Rural Municipality","चौकुने गाउँपालिका",61009],
                    [666,666,"Bajura","Himali Rural Municipality","हिमाली गाउँपालिका",70101],
                    [667,667,"Bajura","Gaumul Rural Municipality","गौमुल गाउँपालिका",70102],
                    [668,668,"Bajura","Budhinanda Municipality","बुढीनन्दा नगरपालिका",70103],
                    [669,669,"Bajura","Swami Kartik Rural Municipality","स्वामी कार्तिक गाउँपालिका",70104],
                    [670,670,"Bajura","Pandab Gufa Rural Municipality","पाण्डव गुफा गाउँपालिका",70105],
                    [671,671,"Bajura","Badimalika Municipality","बडिमालिका नगरपालिका",70106],
                    [672,672,"Bajura","Chhededaha Rural Municipality","छेडेदह गाउँपालिका",70107],
                    [673,673,"Bajura","Budhiganga Municipality","बुढीगंगा नगरपालिका",70108],
                    [674,674,"Bajura","Tribeni Municipality","त्रिवेणी नगरपालिका",70109],
                    [675,675,"Bajhang","Kanda Rural Municipality","काँडा गाउँपालिका",70201],
                    [676,676,"Bajhang","Bungal Municipality","बुंगल नगरपालिका",70202],
                    [677,677,"Bajhang","Surma Rural Municipality","सूर्मा गाउँपालिका",70203],
                    [678,678,"Bajhang","Talkot Rural Municipality","तालकोट गाउँपालिका",70204],
                    [679,679,"Bajhang","Masta Rural Municipality","मष्टा गाउँपालिका",70205],
                    [680,680,"Bajhang","Jayaprithbi Municipality","जयपृथ्वी नगरपालिका",70206],
                    [681,681,"Bajhang","Chhabis Pathibhara Rural Municipality","छबिस पाथिभरा गाउँपालिका",70207],
                    [682,682,"Bajhang","Durgathali Rural Municipality","दुर्गाथली गाउँपालिका",70208],
                    [683,683,"Bajhang","Kedarsyun Rural Municipality","केदारस्युँ गाउँपालिका",70209],
                    [684,684,"Bajhang","Bitthadchir Rural Municipality","बित्थडचिर गाउँपालिका",70210],
                    [685,685,"Bajhang","Thalara Rural Municipality","थलारा गाउँपालिका",70211],
                    [686,686,"Bajhang","Khaptad Chhanna Rural Municipality","खप्तडछान्ना गाउँपालिका",70212],
                    [687,687,"Darchula","Byas Rural Municipality","ब्याँस गाउँपालिका",70301],
                    [688,688,"Darchula","Duhun Rural Municipality","दुहुँ गाउँपालिका",70302],
                    [689,689,"Darchula","Mahakali Municipality","महाकाली नगरपालिका",70303],
                    [690,690,"Darchula","Naugad  Rural Municipality","नौगाड गाउँपालिका",70304],
                    [691,691,"Darchula","Apihimal Rural Municipality","अपिहिमाल गाउँपालिका",70305],
                    [692,692,"Darchula","Marma Rural Municipality","मार्मा गाउँपालिका",70306],
                    [693,693,"Darchula","Shailyashikhar Municipality","शैल्यशिखर नगरपालिका",70307],
                    [694,694,"Darchula","Malikarjun Rural Municipality","मालिकार्जुन गाउँपालिका",70308],
                    [695,695,"Darchula","Lekam Rural Municipality","लेकम गाउँपालिका",70309],
                    [696,696,"Baitadi","Dilasaini Rural Municipality","डीलासैनी गाउँपालिका",70401],
                    [697,697,"Baitadi","Dogada Kedar Rural Municipality","दोगडाकेदार गाउँपालिका",70402],
                    [698,698,"Baitadi","Puchaundi Municipality","पुचौंडी नगरपालिका",70403],
                    [699,699,"Baitadi","Surnaya Rural Municipality","सुर्नया गाउँपालिका",70404],
                    [700,700,"Baitadi","Dasharathchand Municipality","दशरथचन्द नगरपालिका",70405],
                    [701,701,"Baitadi","Pancheshwor Rural Municipality","पन्चेश्वर गाउँपालिका",70406],
                    [702,702,"Baitadi","Shivanath Rural Municipality","शिवनाथ गाउँपालिका",70407],
                    [703,703,"Baitadi","Melauli Municipality","मेलौली नगरपालिका",70408],
                    [704,704,"Baitadi","Patam Municipality","पाटन नगरपालिका",70409],
                    [705,705,"Baitadi","Sigas Rural Municipality","सिगास गाउँपालिका",70410],
                    [706,706,"Dadeldhura","Nawadurga Rural Municipality","नवदुर्गा गाउँपालिका",70501],
                    [707,707,"Dadeldhura","Amargadhi Municipality","अमरगढी नगरपालिका",70502],
                    [708,708,"Dadeldhura","Ajayameru Rural Municipality","अजयमेरु गाउँपालिका",70503],
                    [709,709,"Dadeldhura","Bhageshwor Rural Municipality","भागेश्वर गाउँपालिका",70504],
                    [710,710,"Dadeldhura","Parashuram Municipality","परशुराम नगरपालिका",70505],
                    [711,711,"Dadeldhura","Aalital Rural Municipality","आलिताल गाउँपालिका",70506],
                    [712,712,"Dadeldhura","Ganyapdhura Rural Municipality","गन्यापधुरा गाउँपालिका",70507],
                    [713,713,"Doti","Purbichouki Rural Municipality","पुर्विचौकी गाउँपालिका",70601],
                    [714,714,"Doti","Sayal Rural Municipality","सायल गाउँपालिका",70602],
                    [715,715,"Doti","Aadarsha Rural Municipality","आदर्श गाउँपालिका",70603],
                    [716,716,"Doti","Shikhar Municipality","शिखर नगरपालिका",70604],
                    [717,717,"Doti","Dipayal Silgadhi Municipality","दिपायल सिलगढी नगरपालिका",70605],
                    [718,718,"Doti","K.I. Singh Rural Municipality","के.आई.सिं. गाउँपालिका",70606],
                    [719,719,"Doti","Bogatan Rural Municipality","बोगटान गाउँपालिका",70607],
                    [720,720,"Doti","Badi Kedar Rural Municipality","बडीकेदार गाउँपालिका",70608],
                    [721,721,"Doti","Jorayal Rural Municipality","जोरायल गाउँपालिका",70609],
                    [722,722,"Achham","Panchdebal Binayak Municipality","पंचदेवल बिनायक नगरपालिका",70701],
                    [723,723,"Achham","Ramaroshan Rural Municipality","रामारोशन गाउँपालिका",70702],
                    [724,724,"Achham","Mellekh Rural Municipality","मेल्लेख गाउँपालिका",70703],
                    [725,725,"Achham","Sanphebagar Municipality","साँफेबगर नगरपालिका",70704],
                    [726,726,"Achham","Chaurpati Rural Municipality","चौरपाटी गाउँपालिका",70705],
                    [727,727,"Achham","Mangalsen Municipality","मंगलसेन नगरपालिका",70706],
                    [728,728,"Achham","Bannigadhi Jayagadh Rural Municipality","बान्नीगढी जयगढ गाउँपालिका",70707],
                    [729,729,"Achham","Kamal Bazar Municipality","कमलबजार नगरपालिका",70708],
                    [730,730,"Achham","Dhakari Rural Municipality","ढकारी गाउँपालिका",70709],
                    [731,731,"Achham","Turmakhand Rural Municipality","तुर्माखाँद गाउँपालिका",70710],
                    [732,732,"Kailali","Mohanyal Rural Municipality","मोहन्याल गाउँपालिका",70801],
                    [733,733,"Kailali","Chure Rural Municipality","चुरे गाउँपालिका",70802],
                    [734,734,"Kailali","Godawari Municipality","गोदावरी नगरपालिका",70803],
                    [735,735,"Kailali","Gauriganga Municipality","गौरीगंगा नगरपालिका",70804],
                    [736,736,"Kailali","Ghodaghodi Municipality","घोडाघोडी नगरपालिका",70805],
                    [737,737,"Kailali","Bardagoriya Rural Municipality","बर्दगोरिया गाउँपालिका",70806],
                    [738,738,"Kailali","Lamki Chuha Municipality","लम्कि चुहा नगरपालिका",70807],
                    [739,739,"Kailali","Janaki Rural Municipality","जानकी गाउँपालिका",70808],
                    [740,740,"Kailali","Joshipur Rural Municipality","जोशीपुर गाउँपालिका",70809],
                    [741,741,"Kailali","Tikapur Municipality","टिकापुर नगरपालिका",70810],
                    [742,742,"Kailali","Bhajani Municipality","भजनी नगरपालिका",70811],
                    [743,743,"Kailali","Kailari Rural Municipality","कैलारी गाउँपालिका",70812],
                    [744,744,"Kailali","Dhangadhi Sub-Metropolitian City","धनगढी उपमहानगरपालिका",70813],
                    [745,745,"Kanchanpur","Krishnapur Municipality","कृष्णपुर नगरपालिका",70901],
                    [746,746,"Kanchanpur","Shuklaphanta Municipality","शुक्लाफाँटा नगरपालिका",70902],
                    [747,747,"Kanchanpur","Bedkot Municipality","बेदकोट नगरपालिका",70903],
                    [748,748,"Kanchanpur","Bhimdatta Municipality","भिमदत्त नगरपालिका",70904],
                    [749,749,"Kanchanpur","Mahakali Municipality","माहाकाली नगरपालिका",70905],
                    [750,750,"Kanchanpur","Laljhadi Rural Municipality","लालझाडी गाउँपालिका",70906],
                    [751,751,"Kanchanpur","Punarbas Municipality","पुनर्वास नगरपालिका",70907],
                    [752,752,"Kanchanpur","Belouri Municipality","बेलौरी नगरपालिका",70908],
                    [753,753,"Kanchanpur","Beldandi Rural Municipality","बेलडाँडी गाउँपालिका",70909]
                
            );
            $genders=array(
                ['1','male','पुरुष'],
                ['2','female','महिला'],
                ['3','Third gender','तेश्रो लिङ्गी']
            );
            $blood_groups=array(
                ['1','A+'],
                ['2','O+'],
                ['3','B+'],
                ['4','AB+'],
                ['5','A-'],
                ['6','O-'],
                ['7','B-'],
                ['8','AB-'],
            );
            $woman_marriage_status=array(
                ['1','विवाहीत','married'],
                ['2','अविवाहीत','unmarried'],
                ['3','विधवा','Widow'],
            );
            $marriage_status=array(
                ['1','विवाहीत','married'],
                ['2','अविवाहीत','unmarried']
            );
            $diability_nature_types=array(
                [1,'Physical Disability','शारीरिक असक्षमता'],
                [2,'vision Impairment','दृष्टि बिहिन'],
                [3,'deaf or hard of hearing','बहिरा वा सुन्न गाह्रो।'],
                [4, 'Disability related to voice and speech','स्वर र बोली सम्बन्धी अपाङ्गता'],
                [5, 'Mental Disability','मानसिक अपाङ्गता'],
                [6,'Multiple disability','बहु अपाङ्गता']
            );
            $diability_severity_types=array(
                [1,'A','complete disability','पूर्ण अपाङ्गता','red'],
                [2,'B','severe disability','गम्भीर अपाङ्गता','blue'],
                [3,'C','moderate disability','मध्यम अपाङ्गता','yellow'],
                [2,'B','general disability','सामान्य अपाङ्गता','white'],
            );

            $sifaris_datas=array(
                'palika_name'=>'कुसे',
                'palika_type'=>'गाउँपालिका',
                'palika_pradesh'=>'कर्णाली प्रदेश',
                'district'=>'जाजरकोट',
                'palika_ward_no'=>1,
                'word_address'=>'बरेङ-१,धल्लुबाँस्कोट',
                ''
            );
            View::share('sifaris_datas',$sifaris_datas);
            View::share('provinces',$provinces);
            View::share('districts',$districts);
            View::share('local_bodies',$local_bodies);
            View::share('genders',$genders);
            View::share('blood_groups',$blood_groups);
            View::share('woman_marriage_status',$woman_marriage_status);
            View::share('marriage_status',$marriage_status);
            View::share('diability_nature_types',$diability_nature_types);
            View::share('diability_severity_types',$diability_severity_types);





            $abbreviations=array(
                ['1','श्री','Mr.']
            );
            View::share('abbreviations',$abbreviations);



            $route_np_names=array(
                'home'=>'गृह पृष्ट',
                'edit'=>'एडित',
                'default'=>'दिफौल्ट',
                'create'=>'क्रियेत',

                'sifaris'=>'सिफारिस',
                'aadibasi-pramanit'=>'आदिबासी-प्रमाणित',
                'byabasaya-darkhasta'=>'ब्यबसाय-दरखास्त',
                'briddha-bhatta'=>'बृद्ध-भत्ता',
                'bipanna-nagarik'=>'बिपन्न-नागरिक',
                'form-khareji'=>'फर्म खारेजी',
                'jagga-sagh-simangkan'=>'जग्गाको साँघ सिमाङ्कन',

                'garjagga-namsari-kitani'=>'घर जग्गा नामसारी सिफारिस (किटानी)',
                'gar-kayam-sifaris'=>'घर कायम सिफारिस',
                'garjagga-namsari-sifaris'=>'घर जग्गा नामसारी सिफारिस',
                'gar-janaune-sifaris'=>'घर जनाउने सिफारिस',
                'kittakat-sifaris'=>'कित्ताकाट सिफारिस',
                'gar-bato-pramanit'=>'घरबाटो प्रमाणित',

                'sewa'=>'सेवा',
                'yojana'=>'योजना',
                'parichaya-patra'=>'परिचय पत्र',
                'mahila'=>'महिला',
                'baalbaalika'=>'बालबालिका',
                'apaanga'=>'आपाङ्ग',
                'darta'=>'दर्ता',
                'chalani'=>'चलानी',

                'roles'=>'रोल',
                'users'=>'युजर',
                'settings'=>'सेटिङ',
                'parichaya'=>'परिचय',
                'karmachari'=>'कर्मचारी',
                'ward'=>'वडा',
                'pratinidhi'=>'प्रतिनिधी',
                'patra-kisim'=>'पत्रको किसिम',
                'sakha'=>'साखा',
                'sadasya'=>'सदस्य',
                'nagarikta-pratilipi'=>'नागरिकता प्रतिलिपि',
                'nagarikta-pramanpatra'=>'नागरिकता प्रमाणपत्र',
                'nagarikta-sifaris'=>'नागरिकताको सिफारिस',
                'nagarikta-pramanpatra-frompati'=>'नेपाली नागरिकताको प्रमाण-पत्र(पति)',
                'nepali-angikrit-nagarikta'=>'नेपाली अंगीकृत नागरिकता',
                'nagarikta-pramanpatra-pratilipi'=>'नेपाली नागरिकताको प्रमाण-पत्र प्रतिलिपि',
                'char-killa-sifaris'=>'चार किल्ला सिफारिस',
                'lalpurja-pratilipi-sifaris'=>'लालपुर्जाको प्रतिलिपि सिफारिस',
                'purjama-gar-kayam-sifaris'=>'जग्गाधनी प्रमाण पुर्जामा घर कायम सिफारिस',
                'gar-patal-vayeko-sifaris'=>'घर पाताल भएको सिफारिस',
                'jot-bhok-chalan-sifaris'=>'जोत भोग चलनको सिफारिस',
                'chauhadhi-sifaris'=>'चौहद्दी सिफारिस',



                'kharcha-faatwari-bhiwaran'=>'खार्चा फाटवारी भवारान',
                'yojana-kissim'=>'योजना किसिम',
                'yojana-udesya'=>'योजना उदेशा',
                'yojana-sanchalan-prakriya'=>'योजना संचलन प्रक्रिया',
                'yojana-prakriti'=>'योजना प्रक्रिया',
                'yojana-stara'=>'योजना स्टारा',
                'yojana-kriyakalap'=>'योजना कृयाकलाप',
                'kharid-prakar'=>'खरिड प्रकार',
                'prathmikata-prakar'=>'प्रथमिकता प्रकार',
                'yojana-chanaut-adhar'=>'योजना चनाउट आधार',
                'ranautic-sanket'=>'रानौटिक संकेत',
                'karyakram'=>'कार्यक्रम',
                'ekaiko-prakar'=>'एक्कैको प्रकार',
                'yojana-kramaagat'=>'योजना क्रमागत',
                'yojana-awastha'=>'योजना आवस्ता',
                'thekedar-prakar'=>'ठेकेडर प्रकार',
                'lachit-samaha'=>'लाचित समाहा',




                'gaupalika-nagarpalika'=>'गाउँपालिका/नगरपालिका',
                'palika-parichaya'=>'पालिका परिचय'


            );
            View::share('route_np_names',$route_np_names);
        });








        Validator::extend('phone', function($attribute, $value, $parameters, $validator) {
            return preg_match('%^(?:(?:\(?(?:00|\+)([1-4]\d\d|[1-9]\d?)\)?)?[\-\.\ \\\/]?)?((?:\(?\d{1,}\)?[\-\.\ \\\/]?){0,})(?:[\-\.\ \\\/]?(?:#|ext\.?|extension|x)[\-\.\ \\\/]?(\d+))?$%i', $value) && strlen($value) >= 10;
        });

        Validator::replacer('phone', function($message, $attribute, $rule, $parameters) {
            return str_replace(':attribute',$attribute, 'सहि फोन नुम्बर हल्नुहोस ।');
        });


        Validator::extend('np_phone', function($attribute, $value, $parameters, $validator) {
            $np_en_numbers=array(['1','१'],['2','२'],['3','३'],['4','४'],['5','५'],['6','६'],['7','७'],['8','८'],['9','९'],['0','०']);
            //converts nepali number to english number in the given phone umber so that we can validate
            foreach ($np_en_numbers as $np_en_number)
            {
                $value=str_replace($np_en_number[1], $np_en_number[0], $value);
            }
            $main_phone_no_count=sizeof(mb_str_split($value));
            if (strpos($value,'-'))
            {
                $phone_no=explode('-',$value)[1];
                $main_phone_no_count=sizeof(mb_str_split($phone_no));
            }
            if (strpos($value,' '))
            {
                $phone_no=explode(' ',$value)[1];
                $main_phone_no_count=sizeof(mb_str_split($phone_no));
            }
//            explode()
            //regular expression for nepali phone number formate
            return preg_match("/(?:\+977[- ])?\d{2}[- ]?\d{7,8}$/", $value)&&(7<=$main_phone_no_count&&$main_phone_no_count<=10);
        });

        Validator::replacer('np_phone', function($message, $attribute, $rule, $parameters) {
            return str_replace(':attribute',$attribute, 'सहि मोबाईल/फोन नुम्बर हल्नुहोस ।');
        });


        Validator::extend('np_integer', function($attribute, $value, $parameters, $validator) {
//            return preg_match('/१|२|३|४|५|६|७|८|९|०/i', $value);
            return preg_match("/^[१२३४५६७८९०]+$/",$value);
        });

        Validator::replacer('np_integer', function($message, $attribute, $rule, $parameters) {
            return str_replace(':attribute',$attribute, 'नेपाली अंकमा हुनुपर्छ ।');
        });


        Validator::extend('np_double', function($attribute, $value, $parameters, $validator) {
            return preg_match("/^[१२३४५६७८९०・]+$/", $value);
        });

        Validator::replacer('np_double', function($message, $attribute, $rule, $parameters) {
            return str_replace(':attribute',$attribute, 'अंकमा हुनुपर्छ ।');
        });




    }
}
